#!/usr/bin/env php
<?php

require_once __DIR__ . '/../vendor/autoload.php';

use Symfony\Component\Console\Application;
use DrupalUpdateHelper\UpdateHelperCommand;


$app = new Application();
$app->add(new UpdateHelperCommand());
$app->run();
